config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root to: 'movies#index'
  resources :movies

  # devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Movie, public: true

    if user.present?
      can [:read], Movie, user_id: user.id
      can [:update], Rating, user_id: user.id

      if user.admin?
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movies

  def to_s
    title
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :ratings
  has_many :users, through: :ratings
  belongs_to :category

  paginates_per 10

  def current_rate
    r = ratings.map(&:rate)

    return 0 if r.empty?

    r.sum(&:to_i) / r.count
  end

  def user_rate(user)
    if user && ratings.find_by(user: user).present?
      ratings.find_by(user: user).rate
    else
      current_rate
    end
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :rate, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 10 }
  enum rate: %w[0 1 2 3 4 5 6 7 8 9 10]
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ratings
  has_many :movies, through: :ratings
  belongs_to :role

  before_create :set_default_role

  def to_s
    email
  end

  def admin?
    role.to_s == 'admin'
  end

  def user?
    role.to_s == 'user'
  end

  private

  def set_default_role
    self.role ||= Role.find_by(name: 'user')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: %i[index update]
  before_action :set_movie, only: %i[show edit update destroy]
  before_action :set_rate, only: %i[show edit]
  before_action :set_ratings, :set_categoties

  def index
    @movies = Movie.all

    update_rate(params['movie_id'], params['rate']) if params['movie_id'] && params['rate']

    filter = params[:category]
    category = Category.find_by(title: filter)

    @movies = @movies.where(category_id: category.id) if filter.present? && category
    @movies = @movies.page(params[:page])

    respond_to do |format|
      format.html
      format.json { render html: @movies }
    end
  end

  def new
    @movie = Movie.new
  end

  def edit; end

  def show; end

  def create
    @movie = Movie.new(movie_params)
    @movie.save

    redirect_to movie_path @movie
  end

  def update
    @movie.update(movie_params)

    update_rate('', rating_params['ratings']) if rating_params['ratings'].present? && rating_params['ratings'] != 0
    #   rating = Rating.find_or_initialize_by(movie: @movie, user: current_user)
    #   rating.update(rate: rating_params['ratings'])
    # end

    redirect_to movie_path @movie
  end

  def destroy
    @movie.destroy

    redirect_to movies_path
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def set_rate
    @rate = Rating.find_by(movie_id: @movie.id, user: current_user)&.rate
  end

  def movie_params
    params.require(:movie).permit(:title, :text, :category_id)
  end

  def rating_params
    params.require(:movie).permit(:ratings)
  end

  def set_ratings
    @ratings = Rating.rates.keys
  end

  def set_categoties
    @categories = Category.all
  end

  def filtering_params(params)
    params.slice(:category)
  end

  def update_rate(id, rate)
    movie = @movie || Movie.find(id)
    rating = Rating.find_or_initialize_by(movie: movie, user: current_user)
    rating.update(rate: rate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def rate_options
    [].tap do |a|
      @ratings.each do |k|
        a << [k, k]
      end
    end
  end
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('layout.page_name')
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      div.row
        div.col-md-3
          = link_to t('layout.logo_name') , root_path, :class => 'brand'
        div.col-md-3
          = link_to 'categories', categories_path
        div.col-md-6
          - if current_user
            = t('layout.logged_in_as')
            '
            = link_to "#{current_user}", edit_user_registration_path
            | |
            '
          - if current_user
            = link_to t('layout.log_out'), destroy_user_session_path, :method => 'delete'
          - else
            = link_to t('devise.sessions.sign_in'), new_user_session_path

    .container
      div.row
        = yield

app/views/movies/_form.html.slim
= form_for @movie do |f|
  - if @movie.errors.any?
    #error_explanation
      h2 = "#{pluralize(@movie.errors.count, "error")} prohibited this metric from being saved:"
      ul
        - @movie.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :category_id
    = f.collection_select(:category_id, @categories, :id, :title)
  .field
    = f.label :ratings
    = f.select :ratings, options_for_select(rate_options, @rate)

    Rating.rates.keys
  .actions = f.submit 'save'

app/views/movies/edit.html.slim
h1 Editing metric

- if current_user && current_user.admin?
  == render 'form'

= link_to 'Show', @movie
'|
= link_to 'Back', movies_path

app/views/movies/index.html.slim
div.col-md-4
  h1 Movies

.div.col-md-8
  strong Filter:
  | &nbsp;
  = link_to 'none', :movies
  | &nbsp;
  - @categories.each do |category|
    = link_to category, "#{movies_path}?category=#{category}"
    | &nbsp;



div.col-md-2
  strong Title
div.col-md-4
  strong Text
div.col-md-2
  strong Rate
div.col-md-2
  strong Category
div.col-md-2
  strong Actions

- @movies.each do |movie|
  div.col-md-2
    = movie.title
  div.col-md-4
    = movie.text
  div.col-md-2
    = select_tag 'rating', options_for_select(rate_options, movie.user_rate(current_user)), movie_id: movie.id #, disabled: current_user.present? ? false : true
  div.col-md-2
    = movie.category
  div.col-md-2
    - if current_user && current_user.admin?
      = link_to 'Show', movie
      | &nbsp;
      = link_to 'Edit', edit_movie_path(movie)
      | &nbsp;
      = link_to 'Destroy', movie, data: {:confirm => 'Are you sure?'}, :method => :delete
- if current_user && current_user.admin?
  .row
    div.col.md-12
      = link_to 'Create new movie', new_movie_path

= paginate @movies

app/views/movies/new.html.slim
h1 New movie

== render 'form'

= link_to 'Back', movies_path

app/views/movies/show.html.slim
p
  strong Title:
  = @movie.title
  br
  strong Text:
  = @movie.text
  br
  strong Rating:
  = @movie.current_rate
  br
  strong Category:
  = @movie.category
  br
- if current_user && current_user.admin?
  = link_to 'Edit', edit_movie_path(@movie)
  '|
= link_to 'Back', movies_path